FACULTY = [
    'Biology',
    'Chemistry',
    'Physics',
    'Mathematics',
    'Geography',
    'History',
    'Philology',
    'Sociology',
    'Psychology',
    'Law',
    'Economics',
    'Political Science',
    'Journalism',
    'Education',
    'Physical Education',
    'Engineering',
    'Architecture',
    'Medicine',
    'Dentistry',
    'Veterinary Science',
    'Arts',
    'Theology',
    'Business Administration',
    'Public Administration',
    'Cosmetology',
    'Tourism',
    'Performing Arts',
    'Applied Sciences',
    'Remote Sensing and Space Research',
    'Information Technology',
    'Marine Sciences',
    'Aeronautics',
    'Mining',
]
