DATA = {
    'faculties': [
        'Biology',
        'Chemistry',
        'Physics',
        'Mathematics',
        'Geography',
        'History',
        'Philology',
        'Sociology',
        'Psychology',
        'Law',
        'Economics',
        'Political Science',
        'Journalism',
        'Education',
        'Physical Education',
        'Engineering',
        'Architecture',
        'Medicine',
        'Dentistry',
        'Veterinary Science',
        'Arts',
        'Theology',
        'Business Administration',
        'Public Administration',
        'Cosmetology',
        'Tourism',
        'Performing Arts',
        'Applied Sciences',
        'Remote Sensing and Space Research',
        'Information Technology',
        'Marine Sciences',
        'Aeronautics',
        'Mining',
    ],
    'positions': [
        'Rector',
        'Vice–Rector',
        'Dean',
        'Head of the Department',
        'Professor',
        'Associate Professor',
        'Senior Lecturer',
        'Teacher',
        'Teaching Assistant',
        'Methodologist',
        'Secretary',
        'Laboratory assistant',
        'Librarian',
        'Dormitory Commandant',
        'Security guard',
        'Cleaner',
        'Accountant',
        'Driver',
    ],
    'disciplines': [
        'Mathematics',
        'Physics',
        'Chemistry',
        'Computer science',
        'Biology',
        'Geography',
        'History',
        'Philosophy',
        'Economy',
        'Right',
        'Psychology',
        'Sociology',
        'Political Science',
        'Cultural studies',
        'Foreign languages',
        'Physical Culture',
        'Higher Mathematics',
        'Theoretical mechanics',
        'Resistance of materials',
        'Machine Details',
        'Technology of structural materials',
        'Electrical engineering',
        'Electronics',
        'Heat engineering',
        'Hydraulics',
        'Theory of mechanisms and machines',
        'Metrology, standardization and certification',
    ]
}
