"""update user

Revision ID: d296e1db8e73
Revises: 51e27f0ec3ab
Create Date: 2023-09-12 18:17:16.125055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd296e1db8e73'
down_revision: Union[str, None] = '51e27f0ec3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'bio')
    op.drop_column('student', 'bio')
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'middle_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('student', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
