"""update

Revision ID: db09671185fb
Revises: 
Create Date: 2023-09-12 18:06:05.229236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db09671185fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('female', 'male', 'other', name='gender'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('student',
    sa.Column('curse', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('employee')
    op.drop_table('user')
    # ### end Alembic commands ###
