"""add student field faculty

Revision ID: 8d58ff2354fa
Revises: b79e6aa81f86
Create Date: 2023-09-30 19:56:20.985458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d58ff2354fa'
down_revision: Union[str, None] = 'b79e6aa81f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'specialization')
    op.add_column('student', sa.Column('faculty', sa.String(), nullable=False))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('student', 'faculty')
    op.add_column('employee', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
