"""empl

Revision ID: fc0fc2619902
Revises: 5d2c968230a6
Create Date: 2023-09-13 13:51:55.404603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0fc2619902'
down_revision: Union[str, None] = '5d2c968230a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee', 'position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
