"""add field faculty on student

Revision ID: ce44c2643f7a
Revises: fd49a1e59d21
Create Date: 2023-10-02 14:52:18.173269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce44c2643f7a'
down_revision: Union[str, None] = 'fd49a1e59d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('faculty', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'faculty')
    # ### end Alembic commands ###
