"""update st, emp

Revision ID: 2975b4ab0d8d
Revises: fc0fc2619902
Create Date: 2023-09-24 00:16:06.642868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2975b4ab0d8d'
down_revision: Union[str, None] = 'fc0fc2619902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discipline_student_id_fkey', 'discipline', type_='foreignkey')
    op.drop_constraint('discipline_employee_id_fkey', 'discipline', type_='foreignkey')
    op.drop_column('discipline', 'student_id')
    op.drop_column('discipline', 'employee_id')
    op.add_column('student', sa.Column('faculty_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'student', 'faculty', ['faculty_id'], ['id'])
    op.drop_column('student', 'faculty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('faculty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'faculty_id')
    op.add_column('discipline', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('discipline', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('discipline_employee_id_fkey', 'discipline', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key('discipline_student_id_fkey', 'discipline', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
