"""update

Revision ID: 51e27f0ec3ab
Revises: db09671185fb
Create Date: 2023-09-12 18:09:10.166015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e27f0ec3ab'
down_revision: Union[str, None] = 'db09671185fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('student', sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.add_column('student', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('student', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'created_at')
    op.drop_column('student', 'updated_at')
    op.drop_column('student', 'id')
    op.drop_column('employee', 'created_at')
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'id')
    # ### end Alembic commands ###
